[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "b2b-saas-revops"
version = "0.1.0"
dependencies = [
    "dagster",
    "dagster-cloud",
    "dagster-dbt",
    "dbt-snowflake",
    "dlt[snowflake]",
    "elementary-data[snowflake]",
    "python-dotenv",
    "requests",
    "pandas"
]

[tool.dagster]
module_name = "dagster_pipeline"

[tool.setuptools]
py-modules = ["dagster_pipeline"]
packages = ["ingestion", "scripts"]

