contentType: chart
name: Account Health Distribution
slug: account-health-distribution
tableName: fct_accounts_health
spaceSlug: customer-success
version: 1
metricQuery:
  exploreName: fct_accounts_health
  dimensions:
    - fct_accounts_health_health_status
  metrics:
    - fct_accounts_health_at_risk_accounts
  filters: {}
  sorts: []
  tableCalculations: []
  limit: 500
chartConfig:
  type: pie
