name: Risk Reasons by Account Count
slug: cs-churn-risk-reasons
tableName: fct_accounts_health
spaceSlug: customer-success
metricQuery:
  exploreName: fct_accounts_health
  dimensions:
    - fct_accounts_health_health_reason
  metrics:
    - fct_accounts_health_at_risk_accounts
  filters: {}
  sorts: []
  limit: 500
chartConfig:
  type: bar
