contentType: chart
name: MRR Waterfall (Trailing 12 Months)
slug: mrr-waterfall-by-month
tableName: fct_mrr_waterfall
spaceSlug: finance
version: 1
metricQuery:
  exploreName: fct_mrr_waterfall
  dimensions:
    - fct_mrr_waterfall_month_date
  metrics:
    - fct_mrr_waterfall_total_new_mrr
    - fct_mrr_waterfall_total_churn_mrr
  filters: {}
  sorts: []
  tableCalculations: []
  limit: 500
chartConfig:
  type: cartesian
  config:
    eChartsConfig:
      series:
        - encode:
            xRef:
              field: fct_mrr_waterfall_month_date
            yRef:
              field: fct_mrr_waterfall_total_new_mrr
          type: bar
        - encode:
            xRef:
              field: fct_mrr_waterfall_month_date
            yRef:
              field: fct_mrr_waterfall_total_churn_mrr
          type: bar
    layout:
      xField: fct_mrr_waterfall_month_date
      yField:
        - fct_mrr_waterfall_total_new_mrr
        - fct_mrr_waterfall_total_churn_mrr
