contentType: chart
name: Trials Expiring in 3 Days
slug: product-trial-at-risk
tableName: fct_trial_conversion
spaceSlug: product
version: 1
metricQuery:
  exploreName: fct_trial_conversion
  dimensions:
    - fct_trial_conversion_workspace_id
    - fct_trial_conversion_company_name
  metrics:
    - fct_trial_conversion_trials_at_risk
  filters: {}
  sorts:
    - fieldId: fct_trial_conversion_trials_at_risk
      descending: true
  tableCalculations: []
  limit: 500
chartConfig:
  type: table
