contentType: chart
name: Activation Funnel
slug: product-activation-funnel
tableName: fct_product_activation
spaceSlug: product
version: 1
metricQuery:
  exploreName: fct_product_activation
  dimensions: []
  metrics: 
    - fct_product_activation_total_users_sum
    - fct_product_activation_activated_users_sum
  filters: {}
  sorts: []
  tableCalculations: []
  limit: 500
chartConfig:
  type: cartesian
  config:
    eChartsConfig:
      series:
        - encode:
            yRef:
              field: fct_product_activation_total_users_sum
          name: Total Users
          type: bar
        - encode:
            yRef:
              field: fct_product_activation_activated_users_sum
          name: Activated Users
          type: bar
    layout:
      yField:
        - fct_product_activation_total_users_sum
        - fct_product_activation_activated_users_sum
