contentType: chart
name: Win Rate by Account Segment
slug: sales-win-rate-by-segment
tableName: fct_pipeline
spaceSlug: sales
version: 1
metricQuery:
  exploreName: fct_pipeline
  dimensions:
    - fct_pipeline_account_segment
  metrics:
    - fct_pipeline_total_pipeline_value
  filters: {}
  sorts: []
  tableCalculations: []
  limit: 500
chartConfig:
  type: cartesian
  config:
    eChartsConfig:
      series:
        - encode:
            xRef:
              field: fct_pipeline_account_segment
            yRef:
              field: fct_pipeline_total_pipeline_value
          type: bar
    layout:
      xField: fct_pipeline_account_segment
      yField:
        - fct_pipeline_total_pipeline_value
