contentType: chart
name: Total MRR
slug: total-mrr
tableName: dim_accounts
spaceSlug: executive-overview
version: 1
metricQuery:
  exploreName: dim_accounts
  dimensions: []
  metrics:
    - dim_accounts_total_mrr
  filters: {}
  sorts: []
  tableCalculations: []
  limit: 500
chartConfig:
  type: big_number
